include:
  - local: /configs/gitlab-ci/workflows/feature-fix-branch.gitlab-ci.yml
    rules:
      - if: $CI_COMMIT_REF_NAME =~ /^feature\/|^fix\//
      - if: $CI_COMMIT_REF_NAME == "develop"
  - local: /configs/gitlab-ci/workflows/mr-develop.gitlab-ci.yml
    rules:
      - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"
  - local: /configs/gitlab-ci/workflows/develop.gitlab-ci.yml
    rules:
      - if: $CI_COMMIT_REF_NAME == "develop"

default:
  timeout: 2h

stages:
  - install
  - validate
  - test
  - review
  - start_build
  - start_release
  - build
  - publish

variables:
  # Pipeline config
  MACOS_RUNNER_TAG: "CHANGE_ME"
  CI: "true"
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"
  GIT_STRATEGY: "clone"
  IMG_NODE: "node:18-alpine"
  ENABLE_REVIEW_REQUEST: "yes"
  REVIEWERS_LIST: "CHANGE_ME"
  REVIEW_CHAT_WEBHOOK: "CHANGE_ME"
  BUILD_CHAT_WEBHOOK: "CHANGE_ME"
  PROJECT_MAINTAINER: "CHANGE_ME"
  # Fastlane config
  FASTLANE_SKIP_UPDATE_CHECK: "true"
  FASTLANE_HIDE_CHANGELOG: "true"
  FASTLANE_OPT_OUT_USAGE: "true"
  FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: "30"
  FASTLANE_XCODEBUILD_SETTINGS_RETRIES: "4"
  # Android config
  ENABLE_ANDROID: "yes"
  ANDROID_PROJECT_DIR: "android"
  ANDROID_BUILD_TYPE: "CHANGE_ME"
  GRADLE_HEAP_SIZE_SETTINGS: "2048m"
  # IOS config
  ENABLE_IOS: "yes"
  PILOT_SKIP_WAITING_FOR_BUILD_PROCESSING: "true"
  MATCH_READONLY: "true"
  MATCH_STORAGE_MODE: "git"
  MATCH_GIT_URL: "git@gitlab.cdek.ru:react-native/fastlane-match-storage.git"
  MATCH_GIT_BRANCH:  "master"
  MATCH_PASSWORD:  "SUPER_SECRET"
  IOS_PROJECT_PATH: "ios"
  IOS_PROJECT_WORKSPACE: "CHANGE_ME"
  GYM_WORKSPACE: $IOS_PROJECT_PATH/$IOS_PROJECT_WORKSPACE.xcworkspace
  GYM_CLEAN: "true"
  GYM_OUTPUT_DIRECTORY: $IOS_PROJECT_PATH/build
  GYM_OUTPUT_NAME: "CHANGE_ME"
  GYM_BUILD_PATH: $IOS_PROJECT_PATH/build
  GYM_ARCHIVE_PATH: $IOS_PROJECT_PATH/build/archive
  GYM_DERIVED_DATA_PATH: $IOS_PROJECT_PATH/build/DerivedData
  GYM_BUILDLOG_PATH: $IOS_PROJECT_PATH/build/Logs
  APP_STORE_CONNECT_API_KEY_KEY_ID: "SUPER_SECRET"
  APP_STORE_CONNECT_API_KEY_ISSUER_ID: "SUPER_SECRET"
  APP_STORE_CONNECT_API_KEY_KEY_FILE: "AuthKey.p8"
  APP_STORE_CONNECT_API_KEY_DURATION: "1200"

no_jobs:
  stage: .pre
  rules:
    - when: never
  script:
    - echo "No jobs"
