afterInstall: "node -e \"if (process.env.CI) {process.exit(1)} else {process.exit(0)}\" && npx yarn lefthook install || echo"

compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmRegistryServer: "https://repo.cdek.ru/repository/npm-public"

npmScopes:
  "cdek":
    npmRegistryServer: "https://repo.cdek.ru/repository/npm-private"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-after-install.cjs
    spec: "https://raw.githubusercontent.com/mhassan1/yarn-plugin-after-install/v0.5.0/bundles/@yarnpkg/plugin-after-install.js"

yarnPath: .yarn/releases/yarn-4.5.1.cjs
