nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-after-install.cjs
    spec: "https://raw.githubusercontent.com/mhassan1/yarn-plugin-after-install/v0.5.0/bundles/@yarnpkg/plugin-after-install.js"

afterInstall: npx yarn lefthook install

yarnPath: .yarn/releases/yarn-3.8.5.cjs

npmRegistryServer: "https://repo.cdek.ru/repository/cdek-npm"
