nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-after-install.cjs
    spec: "https://raw.githubusercontent.com/mhassan1/yarn-plugin-after-install/v0.5.0/bundles/@yarnpkg/plugin-after-install.js"

afterInstall: node -e "if (process.env.CI) {process.exit(1)} else {process.exit(0)}" && npx yarn lefthook install || echo

yarnPath: .yarn/releases/yarn-3.8.5.cjs

npmRegistryServer: "https://repo.cdek.ru/repository/cdek-npm"
