include:
  - local: /configs/gitlab-ci/jobs/yarn-install.gitlab-ci.yml

stages:
  - test

variables:
  IMG_NODE: "node:18-alpine"

unit_test:
  stage: test
  interruptible: true
  extends:
    - .yarn_install_dependent_job
  script:
    - npx yarn jest --passWithNoTests --ci --reporters=jest-junit --coverage --coverageReporters text cobertura
  coverage: '/All files[^\|]*\|[^\|]*\s+([\d\.]+)/'
  artifacts:
    expire_in: 1 week
    when: always
    reports:
      junit:
        - junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
