include:
  - local: /configs/gitlab-ci/jobs/yarn-install.gitlab-ci.yml

stages:
  - validate

variables:
  IMG_NODE: "node:18-alpine"

lint:
  stage: validate
  interruptible: true
  extends:
    - .yarn_install_dependent_job
  variables:
    ESLINT_CODE_QUALITY_REPORT: gl-codequality.json
  script:
    - npx yarn eslint --format gitlab .
  artifacts:
    expire_in: 1 week
    when: always
    reports:
      codequality: gl-codequality.json

typecheck:
  stage: validate
  interruptible: true
  extends:
    - .yarn_install_dependent_job
  script:
    - npx yarn tsc --noEmit


