# Docker cache

## Basic

.yarn_docker_cache: &yarn_docker_cache
  key:
    files: 
      - yarn.lock
    prefix: yarn-docker
  paths:
    - node_modules
    - .yarn/cache

## Actual used cache configs

.yarn_docker_cache_pull_push:
  cache:
    - <<: *yarn_docker_cache
      fallback_keys: 
        - yarn-docker
      policy: pull-push

.yarn_docker_cache_pull:
  cache:
    - <<: *yarn_docker_cache
      policy: pull

# MacOS Cache

## Basic

.yarn_macos_cache: &yarn_macos_cache
  key:
    files:
      - package-lock.json
    prefix: yarn-macos
  paths:
    - node_modules
    - .yarn/cache

.ruby_macos_cache: &ruby_macos_cache
  key:
    files:
      - Gemfile.lock
    prefix: ruby-macos
  paths:
    - vendor

.pods_macos_cache: &pods_macos_cache
  key:
    files:
      - ios/Podfile.lock
    prefix: pod
  paths:
    - ios/Pods

## Actual used cache configs
.yarn_macos_cache_pull_push:
  cache:
    - <<: *yarn_macos_cache
      fallback_keys:
        - yarn-macos
      policy: pull-push

.yarn_macos_cache_pull:
  cache:
    - <<: *yarn_macos_cache
      policy: pull

.ruby_macos_cache_pull_push:
  cache:
    - <<: *ruby_macos_cache
      fallback_keys:
        - ruby-macos
      policy: pull-push

.yarn_ruby_macos_cache_pull:
  cache:
    - <<: *yarn_macos_cache
      policy: pull
    - <<: *ruby_macos_cache
      policy: pull

.pods_macos_cache_pull_push:
  cache:
    - <<: *yarn_macos_cache
      policy: pull
    - <<: *ruby_macos_cache
      policy: pull
    - <<: *pods_macos_cache
      fallback_keys:
        - pods-macos
      policy: pull-push

.pods_macos_cache_pull:
  cache:
    - <<: *yarn_macos_cache
      policy: pull
    - <<: *ruby_macos_cache
      policy: pull
    - <<: *pods_macos_cache
      policy: pull
