variables:
  MACOS_RUNNER_TAG: CHANGE_ME
  IMG_NODE: "node:18-alpine"
  IMG_ALPINE: "alpine:3.20"

.node_docker_runner:
  image: $IMG_NODE
  tags:
    - docker

.review_runner:
  tags:
    - $MACOS_RUNNER_TAG

.build_report_runner:
  tags:
    - $MACOS_RUNNER_TAG
