variables:
  MACOS_RUNNER_TAG: CHANGE_ME
  IMG_NODE: "node:18-alpine"
  IMG_ALPINE: "alpine:3.20"
  GRADLE_HEAP_SIZE_SETTINGS: "2048m"

.node_docker_runner:
  image: $IMG_NODE
  tags:
    - docker

.macos_runner:
  tags:
    - $MACOS_RUNNER_TAG
  before_script:
    - bundle config set deployment 'true'
    - bundle config set frozen 'true'

.android_runner:
  tags:
    - $MACOS_RUNNER_TAG
  before_script:
    - bundle config set deployment 'true'
    - bundle config set frozen 'true'
    - echo sdk.dir=/Users/$USER/Library/Android/sdk >> $ANDROID_PROJECT_DIR/local.properties
    - echo org.gradle.jvmargs=-Xmx$GRADLE_HEAP_SIZE_SETTINGS -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 >> $ANDROID_PROJECT_DIR/local.properties

.alpine_docker_runner:
  image: $IMG_ALPINE
  tags:
    - docker
  variables:
    HTTP_PROXY: "http://runner-proxy.cdek.ru:9000"
    NO_PROXY: "repo.cdek.ru"
  before_script:
    - export HTTPS_PROXY="${HTTP_PROXY}"
    - export HTTP_PROXY="${HTTP_PROXY}"
    - export http_proxy="${HTTP_PROXY}"
    - export https_proxy="${HTTP_PROXY}"
    - export all_proxy="${HTTP_PROXY}"
    - export no_proxy="${NO_PROXY}"
    - sed -i 's/dl-cdn.alpinelinux.org/repo.cdek.ru\/repository/g' /etc/apk/repositories
    - apk add --no-cache curl jq bash
