variables:
  MACOS_RUNNER_TAG: CHANGE_ME
  IMG_NODE: "node:18-alpine"
  IMG_ALPINE: "alpine:3.20"

.node_docker_runner:
  image: $IMG_NODE
  tags:
    - docker

.alpine_docker_runner:
  image: $IMG_ALPINE
  tags:
    - docker
  variables:
    HTTP_PROXY: "http://runner-proxy.cdek.ru:9000"
    NO_PROXY: "repo.cdek.ru"
  before_script:
    - export HTTPS_PROXY="${HTTP_PROXY}"
    - export HTTP_PROXY="${HTTP_PROXY}"
    - export http_proxy="${HTTP_PROXY}"
    - export https_proxy="${HTTP_PROXY}"
    - export all_proxy="${HTTP_PROXY}"
    - export no_proxy="${NO_PROXY}"
    - sed -i 's/dl-cdn.alpinelinux.org/repo.cdek.ru\/repository/g' /etc/apk/repositories
    - apk add --no-cache curl jq bash
